services:
  api:
    container_name: api
    image: mhouney/quote_magician_devops_api:latest
    ports:
      - "4000:4000"
    networks:
      - app_network
    environment:
      MONGODB_ATLAS_USERNAME: ${MONGODB_ATLAS_USERNAME}
      MONGODB_ATLAS_PASSWORD: ${MONGODB_ATLAS_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      start_period: 1s
      interval: 3s
      timeout: 3s
      retries: 3
    
  website:
    depends_on: 
      api:
        condition: service_healthy
    container_name: website
    image: mhouney/quote_magician_website:latest
    ports:
      - "5173:5173"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge