name: Continuous Deployment for the Quotes Website

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t mhouney/quote_magician_website:latest .
          docker push mhouney/quote_magician_website:latest
